-- The MVT identity lookup index (run_id, variable, valid_time, river_network_version_id,
-- river_segment_id) carries the same column SET as the primary key, but same set is not
-- same coverage: with `variable` single-valued table-wide it behaves as
-- (run_id, valid_time, rnv, segid) -- a run-scoped time prefix the pkey cannot offer,
-- because the pkey orders rnv/segid ahead of variable/valid_time. The measured consumers
-- of its 5,571 idx_scan are reads: the #1338 pre-drop baseline shows the national-tile
-- typed_values access (services/tiles/mvt.py:603-651) and the source-identity stats probe
-- (mvt.py:530-553) served by Index Only Scans here, both binding run_id + variable +
-- valid_time + rnv with NO basin_version_id, which the retained selected_identity index
-- cannot serve (its 2nd column is basin_version_id). The statically expected post-drop
-- successor for those two reads is the pkey (usable prefix run_id + rnv, remaining
-- predicates as in-index filters), but that is a pre-receipt prediction, not a
-- measurement: the other retained indexes stay live candidates, and the #1338 pre-merge
-- post-drop EXPLAIN gate determines the actual plan. The ingest
-- window DELETE already planned on the pkey pre-drop (baseline Q7), so the write path is
-- not a consumer. So this drop is a measured TRADEOFF, not a redundancy removal. Live
-- node-27 measurement 2026-08-14 (8 chunks aggregated): 162 GB of carrying cost for
-- those 5,571 idx_scan, against 796,096,944 pkey scans over the same window. The residual
-- coverage loss on those two reads is real and their before/after latency is exactly what
-- the #1338 pre-merge EXPLAIN (ANALYZE, BUFFERS) gate measures; if it regresses, the
-- verbatim rollback below re-creates the index.
-- Rollback (verbatim re-create, from 000019):
--   CREATE INDEX IF NOT EXISTS river_timeseries_mvt_identity_lookup_idx ON hydro.river_timeseries (run_id, variable, valid_time, river_network_version_id, river_segment_id);
DROP INDEX CONCURRENTLY IF EXISTS hydro.river_timeseries_mvt_identity_lookup_idx;

-- The valid-time discovery index (run_id, variable, valid_time DESC) is a strict
-- prefix of the index dropped above -- btree scans backwards, so the DESC direction
-- is not a distinction -- and measured 4663 MB for 10,864 idx_scan. Both in-repo
-- discovery surfaces keep a working server: valid_times_for_layer's named-identity
-- branch (services/tiles/mvt.py) is an exact prefix match on the retained
-- river_timeseries_mvt_selected_identity_valid_time_discovery_idx, and its no-basin
-- branch binds no run_id, so it falls to the retained river_timeseries_valid_time_idx
-- (in-repo measured precedent: the SkipScan plan recorded in openspec archive
-- 2026-06-20-refactor-display-overview-bootstrap design).
-- No in-repo migration ever created it: it was created out-of-band directly
-- on node-27, so this file drops an object the migration chain never produced. That
-- makes IF EXISTS load-bearing rather than decorative -- on any database rebuilt
-- from the migration chain (CI, hermetic test DBs, future nodes) the index never
-- existed and this statement must replay as a no-op. Rollback (verbatim re-create,
-- captured from pg_get_indexdef on node-27, 2026-08-14):
--   CREATE INDEX river_timeseries_valid_time_discovery_idx ON hydro.river_timeseries USING btree (run_id, variable, valid_time DESC);
DROP INDEX CONCURRENTLY IF EXISTS hydro.river_timeseries_valid_time_discovery_idx;
