CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS met;
CREATE SCHEMA IF NOT EXISTS hydro;
CREATE SCHEMA IF NOT EXISTS flood;
CREATE SCHEMA IF NOT EXISTS map;
CREATE SCHEMA IF NOT EXISTS ops;
