#!/usr/bin/env python3
"""Report-only repository entropy audit for Governance-4A.

The script intentionally emits signals instead of gates. It reads repository
files, classifies known governance drift families, and never writes
``.entropy-baseline/latest.json`` in the default report modes.
"""


from __future__ import annotations

import argparse
import ast
import fnmatch
import hashlib
import json
import os
import re
import shlex
import stat
import subprocess
import sys
import textwrap
from bisect import bisect_left, bisect_right
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from types import ModuleType
from typing import Any, Iterable, Literal

# `python scripts/governance/audit_repo_entropy.py` (governance.yml, the
# runbooks and tests/test_entropy_audit_report_contract.py all invoke it that
# way) puts `scripts/governance/` on sys.path, not the repository root, so the
# owner package below is not importable without this. Idempotent, and a no-op
# under `import scripts.governance.audit_repo_entropy`.
if str(Path(__file__).resolve().parents[2]) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.governance.entropy_audit import archive_status as _mod_archive_status
from scripts.governance.entropy_audit import check_env_and_tokens as _mod_check_env_and_tokens
from scripts.governance.entropy_audit import check_paths_and_api as _mod_check_paths_and_api
from scripts.governance.entropy_audit import check_stale_routes as _mod_check_stale_routes
from scripts.governance.entropy_audit import check_topology as _mod_check_topology
from scripts.governance.entropy_audit import constants as _mod_constants
from scripts.governance.entropy_audit import facade_guard as _mod_facade_guard
from scripts.governance.entropy_audit import findings as _mod_findings
from scripts.governance.entropy_audit import repo_files as _mod_repo_files
from scripts.governance.entropy_audit import report as _mod_report
from scripts.governance.entropy_audit import route_governing_text as _mod_route_governing_text
from scripts.governance.entropy_audit import route_mentions as _mod_route_mentions
from scripts.governance.entropy_audit import schema as _mod_schema
from scripts.governance.entropy_audit import scoped_context as _mod_scoped_context
from scripts.governance.entropy_audit import structural_budget as _mod_structural_budget
from scripts.governance.entropy_audit import structural_growth as _mod_structural_growth
from scripts.governance.entropy_audit import structural_sources as _mod_structural_sources
from scripts.governance.entropy_audit import structural_surface as _mod_structural_surface
from scripts.governance.entropy_audit import topology_context_rules as _mod_topology_context_rules
from scripts.governance.entropy_audit import topology_display_env as _mod_topology_display_env
from scripts.governance.entropy_audit import topology_predicates as _mod_topology_predicates
from scripts.governance.entropy_audit.archive_status import (
    _archive_status_field_has_required_value,
    _archive_status_fields_are_complete,
    _archive_status_front_matter_fields,
    _archive_status_join_value,
    _archive_status_key_value,
    _archive_status_scalar,
    _archive_status_scope,
    _archive_status_section_block_fields,
    _archive_status_section_end_line,
    _complete_archive_status_marker_ranges,
    _line_has_complete_archive_status_marker,
    _line_starts_markdown_fence,
    _markdown_heading_level,
    _section_archive_status_marker_ranges,
    _whole_document_archive_status_marker_range,
)
from scripts.governance.entropy_audit.check_env_and_tokens import (
    _broad_e2e_mock_line_numbers,
    _check_broad_e2e_mocks,
    _check_display_env_boundaries,
    _check_paused_workflows,
    _check_qhh_diagnostic_tokens,
    _classify_broad_e2e_mock_path,
    _display_yaml_line_ranges,
    _infra_role_env_scan_files,
    _is_display_boundary_context,
    _line_has_display_env_section,
    _path_has_compute_hint,
    _path_has_display_hint,
    _path_is_frontend_generated_artifact,
    _yaml_service_looks_display_facing,
)
from scripts.governance.entropy_audit.check_paths_and_api import (
    _call_is_route_decorator,
    _call_name,
    _check_agent_artifact_ownership,
    _check_apps_api_layer_inversion,
    _check_makefile_toolchain,
    _check_openapi_frontend_type_drift,
    _check_placeholder_paths,
    _check_slurm_gateway_route_leakage,
    _check_tracked_retired_paths,
    _docstring_line_numbers,
    _is_shell_assignment,
    _makefile_line_has_unmanaged_python_tool,
    _name_for_ast,
    _normalized_apps_api_import_modules,
    _path_has_label,
    _placeholder_path_allowlist_reason,
    _retired_active_tree_prefix_for,
    _shell_command_name,
    _shell_command_segments,
    _slurm_gateway_forbidden_call_reason,
    _slurm_gateway_forbidden_path_reason,
    _slurm_gateway_leakage_lines,
    _slurm_gateway_router_name_is_forbidden,
)
from scripts.governance.entropy_audit.check_stale_routes import (
    _check_stale_route_tokens,
    _path_is_legacy_route_token_scope,
    _path_is_route_authority_expanded_scope,
    _stale_route_line_matches,
    _StaleRouteContextFactory,
)
from scripts.governance.entropy_audit.check_topology import (
    _archive_status_front_matter_closing_line,
    _check_production_topology_drift,
    _production_topology_scan_files,
    _topology_authority_list_item_path,
    _topology_authority_path_normalize,
    _topology_authority_paths,
    _topology_contract_context,
    _topology_declared_current_authorities,
    _topology_display_env_context,
    _topology_document_is_non_current,
    _topology_finding,
    _topology_forward_claim_context,
    _topology_line_context,
    _topology_line_declares_document_superseded,
    _topology_local_block_context,
    _topology_node22_writer_claim_context,
    _topology_path_is_archive_or_generated,
    _topology_top_context_declares_whole_document_non_current,
)
from scripts.governance.entropy_audit.constants import (
    ARCHIVE_STATUS_FRONT_MATTER_MAX_LINES,
    ARCHIVE_STATUS_NON_CURRENT_VALUES,
    ARCHIVE_STATUS_RECOGNIZED_FIELDS,
    ARCHIVE_STATUS_REQUIRED_FIELDS,
    ARCHIVE_STATUS_REQUIRED_FIELDS_BY_STATUS,
    AXES,
    BROAD_E2E_API_MOCK_PATTERN,
    CHECK_FAMILIES,
    COMPATIBILITY_FACADE_GUARD_CHECK_ID,
    COMPATIBILITY_FACADE_GUARD_SCHEMA_VERSION,
    COMPATIBILITY_FACADE_PROJECT_IMPORT_ROOTS,
    COMPLETE_ARCHIVE_STATUS_ALLOWLIST_REASON,
    HARD_GATE_CHECK_IDS,
    HASH_CHUNK_BYTES,
    HYDROMET_PAGE_IDENTIFIER_PATTERN,
    LEGACY_DISPLAY_ROUTE_BOUNDARY_PATTERN,
    LEGACY_DISPLAY_ROUTE_PATTERN,
    LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN,
    LEGACY_DISPLAY_ROUTE_TOKENS,
    MARKDOWN_BLOCKQUOTE_PREFIX_PATTERN,
    MARKDOWN_HEADING_PATTERN,
    MARKDOWN_LIST_ITEM_PATTERN,
    MARKDOWN_TABLE_SEPARATOR_PATTERN,
    MAX_ARTIFACT_FINGERPRINT_BYTES,
    MAX_SCANNED_TEXT_FILE_BYTES,
    PRIORITY_RANK,
    RANK_SCORE,
    RETIRED_ACTIVE_TREE_PREFIXES,
    ROUTE_ACTIVE_CLAUSE_CONNECTOR_PATTERN,
    ROUTE_BASE_PLACEHOLDER_PATTERN,
    ROUTE_REDIRECT_TARGET_PATTERN,
    ROUTE_REDIRECT_WORD_PATTERN,
    ROUTE_VALUED_LEGACY_DISPLAY_ROUTE_PATTERN,
    SCAN_SKIP_DIRS,
    SCAN_SKIP_PREFIXES,
    SCAN_SKIP_ROOT_DIRS,
    SCOPED_AGENT_CONTEXT_CHECK_ID,
    SCOPED_AGENT_CONTEXT_GLOSSARY_PATH,
    SCOPED_AGENT_CONTEXT_SCHEMA_VERSION,
    SCOPED_AGENT_CONTEXT_SPEC_PATH,
    SCORE_RANK,
    SEVERITY_RANK,
    STRUCTURAL_BUDGET_BASE_REF_ENV,
    STRUCTURAL_CJS_EXPORTS_ASSIGNMENT_PATTERN,
    STRUCTURAL_CJS_MODULE_EXPORTS_DEFAULT_PATTERN,
    STRUCTURAL_CJS_MODULE_EXPORTS_OBJECT_START_PATTERN,
    STRUCTURAL_COMPATIBILITY_PATTERN,
    STRUCTURAL_DEPENDENCY_LOCKFILE_NAMES,
    STRUCTURAL_DIFF_HUNK_PATTERN,
    STRUCTURAL_DIFF_MAX_LINE_BYTES,
    STRUCTURAL_DIFF_READ_CHUNK_BYTES,
    STRUCTURAL_FILE_BUDGET_MANDATORY_OVER_LINES,
    STRUCTURAL_FILE_BUDGET_SCHEMA_VERSION,
    STRUCTURAL_FILE_BUDGET_TOP_LIMIT,
    STRUCTURAL_FILE_BUDGET_YELLOW_MIN_LINES,
    STRUCTURAL_FIXTURE_LABELS,
    STRUCTURAL_GENERATED_HEADER_BYTES,
    STRUCTURAL_GENERATED_HEADER_LINES,
    STRUCTURAL_GENERATED_LABELS,
    STRUCTURAL_IMPORT_FAMILY_MIXED_COUNT,
    STRUCTURAL_PARSER_VALIDATOR_PATTERN,
    STRUCTURAL_PROTOCOL_ROOTS,
    STRUCTURAL_PUBLIC_SURFACE_DETAIL_TOKEN_LIMIT,
    STRUCTURAL_PUBLIC_TS_PATTERN,
    STRUCTURAL_PYTHON_CONTEXT_MAX_LINES,
    STRUCTURAL_PYTHON_DECLARATION_PATTERN,
    STRUCTURAL_ROUTE_ENTRYPOINT_PATTERN,
    STRUCTURAL_ROUTE_OWNER_ASSIGNMENT_PATTERN,
    STRUCTURAL_SOURCE_EXTENSIONS,
    STRUCTURAL_SOURCE_FILENAMES,
    STRUCTURAL_SOURCE_ROOTS,
    STRUCTURAL_TOKEN_COMPONENT_MAX_CHARS,
    STRUCTURAL_TOKEN_HASH_HEX_CHARS,
    STRUCTURAL_TS_DEFAULT_EXPORT_PATTERN,
    STRUCTURAL_TS_DYNAMIC_IMPORT_PATTERN,
    STRUCTURAL_TS_EXPORTED_CLASS_PATTERN,
    STRUCTURAL_TS_NAMED_EXPORT_PATTERN,
    STRUCTURAL_TS_REQUIRE_PATTERN,
    STRUCTURAL_TS_STATIC_BARE_IMPORT_PATTERN,
    STRUCTURAL_TS_STATIC_FROM_IMPORT_PATTERN,
    STRUCTURAL_TS_STATIC_IMPORT_MAX_BLOCK_LINES,
    TEXT_EXTENSIONS,
    TOPOLOGY_DISPLAY_ENV_PATH_PATTERN,
    TOPOLOGY_DISPLAY_ENV_SOURCE_TO_WRITER_MAX_LINES,
    TOPOLOGY_PSQL_HEREDOC_MAX_LOOKAHEAD,
    TOPOLOGY_SQL_MUTATION_VERB_PATTERN,
)
from scripts.governance.entropy_audit.facade_guard import (
    _compatibility_attribute_parts,
    _compatibility_expression_is_owner_call,
    _compatibility_facade_alias,
    _compatibility_facade_aliases,
    _compatibility_facade_aliases_for_target_value,
    _compatibility_facade_assignment_aliases,
    _compatibility_facade_definitions,
    _compatibility_facade_guard_findings,
    _compatibility_facade_guard_markdown_lines,
    _compatibility_facade_guard_summary,
    _compatibility_facade_imported_symbols,
    _compatibility_facade_module_aliases,
    _compatibility_facade_owner_attribute,
    _compatibility_facade_signal,
    _compatibility_facade_signal_record,
    _compatibility_facade_signals,
    _compatibility_facade_surface,
    _compatibility_function_effective_body,
    _compatibility_function_is_forwarding,
    _compatibility_imported_name_is_module,
    _compatibility_inventory_contains_token,
    _compatibility_inventory_covers_signal,
    _compatibility_inventory_guard_hook_text,
    _compatibility_inventory_has_follow_up_issue_semantics,
    _compatibility_inventory_has_justification_semantics,
    _compatibility_inventory_has_no_ownership_inversion_semantics,
    _compatibility_inventory_has_owner_hosting_rationale_semantics,
    _compatibility_inventory_has_owner_semantics,
    _compatibility_inventory_has_removal_condition_semantics,
    _compatibility_inventory_has_retention_semantics,
    _compatibility_inventory_has_verification_semantics,
    _compatibility_inventory_line_covers_signal,
    _compatibility_inventory_line_has_metadata,
    _compatibility_project_import_family,
    _compatibility_project_module,
    _compatibility_sequence_elements,
    _compatibility_symbol_signal_type,
)
from scripts.governance.entropy_audit.findings import (
    _allowlist_key,
    _allowlist_reason_key,
    _allowlist_state,
    _boolean_count_by,
    _count_by,
    _count_by_with_defaults,
    _dedupe_findings,
    _finding_record,
    _high_spread_patterns,
    _module_heatmap,
    _normalized_reason_text,
    _slug,
    _summary_counts,
)
from scripts.governance.entropy_audit.repo_files import (
    _artifact_fingerprint_pair_reason,
    _bounded_artifact_sha256,
    _existing_files,
    _file_sha256,
    _git_merge_base,
    _git_resolve_commit,
    _git_tracked_paths,
    _has_scannable_text_name,
    _is_scannable_dir,
    _iter_python_files,
    _iter_text_files,
    _matching_lines,
    _module_for_path,
    _module_for_relative,
    _read_repo_text,
    _rel,
    _repo_relative_path_is_skipped,
    _repo_text_rejection_reason,
)
from scripts.governance.entropy_audit.report import (
    _collect_findings,
    _exit_code_for_report,
    _hard_gate_failing_count,
    _metadata,
    build_report,
    main,
    render_markdown,
    repo_root_from,
)
from scripts.governance.entropy_audit.route_governing_text import (
    _frontend_e2e_legacy_route_context_allowlist,
    _historical_route_authority_banner_line_numbers,
    _hydromet_page_historical_context,
    _line_continues_previous,
    _line_continues_route_paragraph,
    _line_has_active_route_instruction_context,
    _line_has_active_route_valued_context,
    _line_has_compatibility_context,
    _line_has_current_route_governing_context,
    _line_has_evidence_boundary_context,
    _line_has_historical_context,
    _line_has_redirect_alias_context,
    _line_has_route_redirect_arrow,
    _line_has_terse_active_route_context,
    _line_is_list_or_list_continuation,
    _line_is_markdown_table_row,
    _line_starts_markdown_heading,
    _line_starts_markdown_list_item,
    _line_starts_new_current_section,
    _line_wraps_to_next,
    _list_item_end_index,
    _list_item_indent_width,
    _list_item_start_index,
    _markdown_blockquote_depth,
    _markdown_context_line,
    _markdown_context_stripped,
    _markdown_indent_width,
    _markdown_section_headings,
    _parent_list_item_indexes,
    _path_uses_markdown_route_context,
    _period_is_sentence_boundary,
    _preceding_context_lines,
    _route_arrow_points_from_token,
    _route_arrow_points_to_token,
    _same_list_item_following_lines,
    _section_heading_at,
    _stale_route_context_class,
    _stale_route_governing_mention_text,
    _stale_route_governing_text,
    _stale_route_list_governing_text,
    _stale_route_list_governing_text_for_range,
    _stale_route_list_redirect_governing_text,
    _stale_route_list_redirect_governing_text_for_range,
    _stale_route_list_redirect_governing_texts,
    _stale_route_paragraph_governing_text,
    _stale_route_paragraph_governing_text_for_range,
    _stale_route_redirect_governing_text_for_line,
    _stale_route_redirect_governing_texts,
    _stale_route_structural_context,
    _stale_route_table_governing_text,
    _stale_route_table_governing_text_for_range,
    _stale_route_table_redirect_governing_text,
    _text_has_historical_marker,
    _text_has_route_authority_marker,
)
from scripts.governance.entropy_audit.route_mentions import (
    _clause_has_per_mention_redirect_syntax,
    _record_stale_route_mention_facts,
    _route_arrow_shape_for_bounds,
    _route_arrow_shape_near_token,
    _route_redirect_connector_segment,
    _route_token_is_route_valued,
    _split_stale_route_active_clause_connectors,
    _stale_route_allowlist_reason,
    _stale_route_clause_analysis,
    _stale_route_clause_ranges,
    _stale_route_connector_splits_clause,
    _stale_route_duplicate_key,
    _stale_route_join_redirect_text,
    _stale_route_line_context,
    _stale_route_line_contexts,
    _stale_route_mention_clause_bounds,
    _stale_route_mention_context,
    _stale_route_mention_context_key,
    _stale_route_mention_facts,
    _stale_route_mention_facts_by_span,
    _stale_route_mention_has_redirect_syntax,
    _stale_route_mention_has_redirect_syntax_from_analysis,
    _stale_route_mention_redirect_span,
    _stale_route_mention_redirect_span_from_analysis,
    _stale_route_mention_redirect_span_from_facts,
    _stale_route_mention_redirect_text,
    _stale_route_mention_semantic_key,
    _stale_route_precomputed_semantic_key,
    _stale_route_redirect_governing_text,
)
from scripts.governance.entropy_audit.schema import (
    COMPATIBILITY_FACADE_CONFIGS,
    SCOPED_AGENT_CONTEXT_CONFIGS,
    AllowlistState,
    AuditMode,
    FindingAxis,
    FindingSpec,
    StructuralBudgetClass,
    _ArchiveStatusMarkerRange,
    _BoundedGitBlobText,
    _CompatibilityFacadeAlias,
    _CompatibilityFacadeConfig,
    _CompatibilityFacadeDefinition,
    _CompatibilityFacadeImportedSymbol,
    _CompatibilityFacadeSignal,
    _CompatibilityFacadeSurface,
    _ScopedAgentContextConfig,
    _StaleRouteClauseAnalysis,
    _StaleRouteDuplicateKey,
    _StaleRouteLineContext,
    _StaleRouteLineMatch,
    _StaleRouteMentionContext,
    _StaleRouteMentionFacts,
    _StaleRouteStructuralContext,
    _StructuralAddedLine,
    _StructuralAddedLines,
    _StructuralBudgetExemption,
    _StructuralBudgetFile,
    _StructuralComparisonBase,
    _StructuralFileExemption,
    _StructuralOwnershipGrowthSignal,
    _StructuralPhysicalLineCount,
    _StructuralUnknownLineCountFile,
    _TopologyDisplayEnvFacts,
    _TopologyDisplayEnvSource,
    _TopologyDisplayEnvWriterUse,
)
from scripts.governance.entropy_audit.scoped_context import (
    _missing_text_needles,
    _normalize_scoped_context_text,
    _scoped_agent_context_finding_title,
    _scoped_agent_context_findings,
    _scoped_agent_context_markdown_lines,
    _scoped_agent_context_owner_action,
    _scoped_agent_context_record,
    _scoped_agent_context_scope_record,
    _scoped_agent_context_signal,
    _scoped_agent_context_summary,
    _text_contains_needle,
)
from scripts.governance.entropy_audit.structural_budget import (
    _structural_comparison_base,
    _structural_comparison_base_record,
    _structural_file_budget_markdown_lines,
    _structural_file_budget_summary,
)
from scripts.governance.entropy_audit.structural_growth import (
    _git_added_lines,
    _git_blob_text,
    _git_blob_text_prefix,
    _matching_structural_added_lines,
    _read_structural_python_line_ranges,
    _structural_budget_exemption_record,
    _structural_budget_file_record,
    _structural_budget_owner_action,
    _structural_budget_review_reason,
    _structural_diff_truncation_detail,
    _structural_growth_signal,
    _structural_growth_signal_record,
    _structural_import_family_detail,
    _structural_import_family_detail_token,
    _structural_new_public_surface_tokens,
    _structural_ownership_growth_signals,
    _structural_public_surface_detail,
    _structural_python_current_context_public_surface_tokens,
    _structural_top_oversized_files_by_module,
    _structural_top_oversized_modules,
    _structural_unknown_line_count_file_record,
    _summarize_added_line_matches,
)
from scripts.governance.entropy_audit.structural_sources import (
    _physical_line_count,
    _read_structural_analysis_text,
    _read_structural_header_text,
    _structural_added_import_families,
    _structural_bounded_import_families,
    _structural_bounded_token_component,
    _structural_brace_index,
    _structural_current_import_families,
    _structural_import_families,
    _structural_import_family,
    _structural_line_spans,
    _structural_path_is_source_like,
    _structural_path_labels,
    _structural_physical_line_count,
    _structural_python_added_import_families,
    _structural_python_import_block_families,
    _structural_python_import_families,
    _structural_python_import_families_from_tree,
    _structural_python_import_paren_balance,
    _structural_source_exemption,
    _structural_source_rejection_reason,
    _structural_tracked_source_paths,
    _structural_ts_ignored_spans,
    _structural_ts_import_families,
    _structural_ts_line_starts_static_import,
    _structural_ts_position_is_ignored,
    _structural_ts_regex_literal_allowed_at,
    _structural_ts_regex_literal_end,
    _structural_ts_static_import_blocks,
    _structural_ts_static_import_can_continue,
    _structural_ts_static_import_module,
)
from scripts.governance.entropy_audit.structural_surface import (
    _structural_bounded_detail_token,
    _structural_bounded_public_surface_tokens,
    _structural_cjs_module_exports_object_bodies,
    _structural_cjs_object_export_tokens,
    _structural_current_public_surface_tokens,
    _structural_next_open_brace,
    _structural_ownership_surface_signals,
    _structural_public_entrypoint_names,
    _structural_public_surface_label,
    _structural_public_surface_tokens,
    _structural_python_partial_public_surface_tokens,
    _structural_python_public_name,
    _structural_python_public_surface_tokens,
    _structural_route_entrypoint_tokens,
    _structural_route_owner_name_is_allowed,
    _structural_route_owner_names,
    _structural_route_path_token,
    _structural_split_top_level_object_items,
    _structural_ts_class_method_line_match,
    _structural_ts_class_method_names,
    _structural_ts_exported_class_method_tokens,
    _structural_ts_named_export_tokens,
    _structural_ts_public_surface_tokens,
)
from scripts.governance.entropy_audit.topology_context_rules import (
    _topology_context_has_complete_node22_local_pg_boundary,
    _topology_context_has_current_node22_local_postgres_use,
    _topology_context_has_negated_archive_or_stop_state,
    _topology_context_has_negative_mirror_boundary,
    _topology_context_has_node22_local_postgres_use_action,
    _topology_context_has_stale_pending_retirement_state,
    _topology_context_has_unnegated_archived_state,
    _topology_context_has_unnegated_stopped_state,
    _topology_context_is_compatibility_mirror_contract,
    _topology_context_is_explicit_mirror_implementation,
    _topology_context_is_guardrail_or_test_meta,
    _topology_context_is_historical_receipt_evidence,
    _topology_context_is_non_current,
    _topology_context_is_pre_cutover_historical_evidence,
    _topology_context_is_retirement_or_rejection_boundary,
    _topology_context_is_structured_node22_local_pg_boundary,
    _topology_line_has_node22_database_url_scan_drift,
    _topology_line_has_node22_db_writer_drift,
    _topology_line_has_non_current_or_compatibility_marker,
    _topology_local_postgres_context_is_allowed,
    _topology_node22_db_writer_clause_is_allowed,
    _topology_node22_db_writer_context_is_allowed,
)
from scripts.governance.entropy_audit.topology_display_env import (
    _topology_context_has_data_plane_writer_or_mirror_terms,
    _topology_context_has_direct_display_env_source,
    _topology_context_has_display_env_authority_prose,
    _topology_context_has_display_env_prohibition,
    _topology_context_has_indirect_display_env_source,
    _topology_context_has_negative_writer_or_mirror_terms,
    _topology_context_has_unnegated_display_env_source,
    _topology_context_references_display_env_path,
    _topology_context_sources_display_env,
    _topology_display_env_associated_writer,
    _topology_display_env_association_context,
    _topology_display_env_context_is_allowed,
    _topology_display_env_facts,
    _topology_display_env_file_allows_file_level_association,
    _topology_line_display_env_alias_name,
    _topology_line_has_data_plane_writer_command,
    _topology_line_has_psql_context_mutation_command,
    _topology_line_has_psql_mutation_command,
    _topology_line_has_shell_source_command,
    _topology_line_has_unnegated_data_plane_writer_or_mirror_use,
    _topology_line_has_unnegated_direct_display_env_source,
    _topology_line_invokes_psql,
    _topology_line_is_comment_only,
    _topology_line_may_source_display_env,
    _topology_line_sources_display_env,
    _topology_line_sources_display_env_alias,
    _topology_prefix_has_display_env_source_negation,
    _topology_psql_heredoc_token,
    _topology_strip_shell_comment,
)
from scripts.governance.entropy_audit.topology_predicates import (
    _topology_context_has_negative_node22_db_access,
    _topology_context_has_negative_node22_writer_boundary,
    _topology_line_has_node22_local_postgres_or_mirror_drift,
    _topology_line_is_object_store_copy,
    _topology_line_is_standalone_node22_anchor,
    _topology_line_may_have_node22_db_writer_drift,
    _topology_line_may_start_node22_db_writer_claim,
    _topology_line_mentions_mirror,
    _topology_line_mentions_rollback,
    _topology_mentions_active_primary_database_authority,
    _topology_mentions_database,
    _topology_mentions_node22,
    _topology_mentions_writer,
    _topology_node22_db_writer_drift_clauses,
    _topology_normalized,
    _topology_relation_clauses,
    _topology_strip_db_absence_claims,
)

# Re-exported verbatim: the pre-split namespace, name for name. Declared
# here rather than left implicit so F401 stays on for anything this facade
# stops owning, and so the mirror table below has a reviewed input set.
__all__ = [
    "ARCHIVE_STATUS_FRONT_MATTER_MAX_LINES", "ARCHIVE_STATUS_NON_CURRENT_VALUES",
    "ARCHIVE_STATUS_RECOGNIZED_FIELDS", "ARCHIVE_STATUS_REQUIRED_FIELDS",
    "ARCHIVE_STATUS_REQUIRED_FIELDS_BY_STATUS", "AXES", "AllowlistState", "Any", "AuditMode",
    "BROAD_E2E_API_MOCK_PATTERN", "CHECK_FAMILIES", "COMPATIBILITY_FACADE_CONFIGS",
    "COMPATIBILITY_FACADE_GUARD_CHECK_ID", "COMPATIBILITY_FACADE_GUARD_SCHEMA_VERSION",
    "COMPATIBILITY_FACADE_PROJECT_IMPORT_ROOTS", "COMPLETE_ARCHIVE_STATUS_ALLOWLIST_REASON", "FindingAxis",
    "FindingSpec", "HARD_GATE_CHECK_IDS", "HASH_CHUNK_BYTES", "HYDROMET_PAGE_IDENTIFIER_PATTERN", "Iterable",
    "LEGACY_DISPLAY_ROUTE_BOUNDARY_PATTERN", "LEGACY_DISPLAY_ROUTE_PATTERN", "LEGACY_DISPLAY_ROUTE_TOKENS",
    "LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN", "Literal", "MARKDOWN_BLOCKQUOTE_PREFIX_PATTERN",
    "MARKDOWN_HEADING_PATTERN", "MARKDOWN_LIST_ITEM_PATTERN", "MARKDOWN_TABLE_SEPARATOR_PATTERN",
    "MAX_ARTIFACT_FINGERPRINT_BYTES", "MAX_SCANNED_TEXT_FILE_BYTES", "ModuleType", "PRIORITY_RANK", "Path",
    "RANK_SCORE", "RETIRED_ACTIVE_TREE_PREFIXES", "ROUTE_ACTIVE_CLAUSE_CONNECTOR_PATTERN",
    "ROUTE_BASE_PLACEHOLDER_PATTERN", "ROUTE_REDIRECT_TARGET_PATTERN", "ROUTE_REDIRECT_WORD_PATTERN",
    "ROUTE_VALUED_LEGACY_DISPLAY_ROUTE_PATTERN", "SCAN_SKIP_DIRS", "SCAN_SKIP_PREFIXES", "SCAN_SKIP_ROOT_DIRS",
    "SCOPED_AGENT_CONTEXT_CHECK_ID", "SCOPED_AGENT_CONTEXT_CONFIGS", "SCOPED_AGENT_CONTEXT_GLOSSARY_PATH",
    "SCOPED_AGENT_CONTEXT_SCHEMA_VERSION", "SCOPED_AGENT_CONTEXT_SPEC_PATH", "SCORE_RANK", "SEVERITY_RANK",
    "STRUCTURAL_BUDGET_BASE_REF_ENV", "STRUCTURAL_CJS_EXPORTS_ASSIGNMENT_PATTERN",
    "STRUCTURAL_CJS_MODULE_EXPORTS_DEFAULT_PATTERN", "STRUCTURAL_CJS_MODULE_EXPORTS_OBJECT_START_PATTERN",
    "STRUCTURAL_COMPATIBILITY_PATTERN", "STRUCTURAL_DEPENDENCY_LOCKFILE_NAMES", "STRUCTURAL_DIFF_HUNK_PATTERN",
    "STRUCTURAL_DIFF_MAX_LINE_BYTES", "STRUCTURAL_DIFF_READ_CHUNK_BYTES",
    "STRUCTURAL_FILE_BUDGET_MANDATORY_OVER_LINES", "STRUCTURAL_FILE_BUDGET_SCHEMA_VERSION",
    "STRUCTURAL_FILE_BUDGET_TOP_LIMIT", "STRUCTURAL_FILE_BUDGET_YELLOW_MIN_LINES", "STRUCTURAL_FIXTURE_LABELS",
    "STRUCTURAL_GENERATED_HEADER_BYTES", "STRUCTURAL_GENERATED_HEADER_LINES", "STRUCTURAL_GENERATED_LABELS",
    "STRUCTURAL_IMPORT_FAMILY_MIXED_COUNT", "STRUCTURAL_PARSER_VALIDATOR_PATTERN", "STRUCTURAL_PROTOCOL_ROOTS",
    "STRUCTURAL_PUBLIC_SURFACE_DETAIL_TOKEN_LIMIT", "STRUCTURAL_PUBLIC_TS_PATTERN",
    "STRUCTURAL_PYTHON_CONTEXT_MAX_LINES", "STRUCTURAL_PYTHON_DECLARATION_PATTERN",
    "STRUCTURAL_ROUTE_ENTRYPOINT_PATTERN", "STRUCTURAL_ROUTE_OWNER_ASSIGNMENT_PATTERN",
    "STRUCTURAL_SOURCE_EXTENSIONS", "STRUCTURAL_SOURCE_FILENAMES", "STRUCTURAL_SOURCE_ROOTS",
    "STRUCTURAL_TOKEN_COMPONENT_MAX_CHARS", "STRUCTURAL_TOKEN_HASH_HEX_CHARS",
    "STRUCTURAL_TS_DEFAULT_EXPORT_PATTERN", "STRUCTURAL_TS_DYNAMIC_IMPORT_PATTERN",
    "STRUCTURAL_TS_EXPORTED_CLASS_PATTERN", "STRUCTURAL_TS_NAMED_EXPORT_PATTERN", "STRUCTURAL_TS_REQUIRE_PATTERN",
    "STRUCTURAL_TS_STATIC_BARE_IMPORT_PATTERN", "STRUCTURAL_TS_STATIC_FROM_IMPORT_PATTERN",
    "STRUCTURAL_TS_STATIC_IMPORT_MAX_BLOCK_LINES", "StructuralBudgetClass", "TEXT_EXTENSIONS",
    "TOPOLOGY_DISPLAY_ENV_PATH_PATTERN", "TOPOLOGY_DISPLAY_ENV_SOURCE_TO_WRITER_MAX_LINES",
    "TOPOLOGY_PSQL_HEREDOC_MAX_LOOKAHEAD", "TOPOLOGY_SQL_MUTATION_VERB_PATTERN", "UTC", "_ArchiveStatusMarkerRange",
    "_BoundedGitBlobText", "_CompatibilityFacadeAlias", "_CompatibilityFacadeConfig",
    "_CompatibilityFacadeDefinition", "_CompatibilityFacadeImportedSymbol", "_CompatibilityFacadeSignal",
    "_CompatibilityFacadeSurface", "_ScopedAgentContextConfig", "_StaleRouteClauseAnalysis",
    "_StaleRouteContextFactory", "_StaleRouteDuplicateKey", "_StaleRouteLineContext", "_StaleRouteLineMatch",
    "_StaleRouteMentionContext", "_StaleRouteMentionFacts", "_StaleRouteStructuralContext", "_StructuralAddedLine",
    "_StructuralAddedLines", "_StructuralBudgetExemption", "_StructuralBudgetFile", "_StructuralComparisonBase",
    "_StructuralFileExemption", "_StructuralOwnershipGrowthSignal", "_StructuralPhysicalLineCount",
    "_StructuralUnknownLineCountFile", "_TopologyDisplayEnvFacts", "_TopologyDisplayEnvSource",
    "_TopologyDisplayEnvWriterUse", "_allowlist_key", "_allowlist_reason_key", "_allowlist_state",
    "_archive_status_field_has_required_value", "_archive_status_fields_are_complete",
    "_archive_status_front_matter_closing_line", "_archive_status_front_matter_fields",
    "_archive_status_join_value", "_archive_status_key_value", "_archive_status_scalar", "_archive_status_scope",
    "_archive_status_section_block_fields", "_archive_status_section_end_line", "_artifact_fingerprint_pair_reason",
    "_boolean_count_by", "_bounded_artifact_sha256", "_broad_e2e_mock_line_numbers", "_call_is_route_decorator",
    "_call_name", "_check_agent_artifact_ownership", "_check_apps_api_layer_inversion", "_check_broad_e2e_mocks",
    "_check_display_env_boundaries", "_check_makefile_toolchain", "_check_openapi_frontend_type_drift",
    "_check_paused_workflows", "_check_placeholder_paths", "_check_production_topology_drift",
    "_check_qhh_diagnostic_tokens", "_check_slurm_gateway_route_leakage", "_check_stale_route_tokens",
    "_check_tracked_retired_paths", "_classify_broad_e2e_mock_path", "_clause_has_per_mention_redirect_syntax",
    "_collect_findings", "_compatibility_attribute_parts", "_compatibility_expression_is_owner_call",
    "_compatibility_facade_alias", "_compatibility_facade_aliases",
    "_compatibility_facade_aliases_for_target_value", "_compatibility_facade_assignment_aliases",
    "_compatibility_facade_definitions", "_compatibility_facade_guard_findings",
    "_compatibility_facade_guard_markdown_lines", "_compatibility_facade_guard_summary",
    "_compatibility_facade_imported_symbols", "_compatibility_facade_module_aliases",
    "_compatibility_facade_owner_attribute", "_compatibility_facade_signal", "_compatibility_facade_signal_record",
    "_compatibility_facade_signals", "_compatibility_facade_surface", "_compatibility_function_effective_body",
    "_compatibility_function_is_forwarding", "_compatibility_imported_name_is_module",
    "_compatibility_inventory_contains_token", "_compatibility_inventory_covers_signal",
    "_compatibility_inventory_guard_hook_text", "_compatibility_inventory_has_follow_up_issue_semantics",
    "_compatibility_inventory_has_justification_semantics",
    "_compatibility_inventory_has_no_ownership_inversion_semantics",
    "_compatibility_inventory_has_owner_hosting_rationale_semantics",
    "_compatibility_inventory_has_owner_semantics", "_compatibility_inventory_has_removal_condition_semantics",
    "_compatibility_inventory_has_retention_semantics", "_compatibility_inventory_has_verification_semantics",
    "_compatibility_inventory_line_covers_signal", "_compatibility_inventory_line_has_metadata",
    "_compatibility_project_import_family", "_compatibility_project_module", "_compatibility_sequence_elements",
    "_compatibility_symbol_signal_type", "_complete_archive_status_marker_ranges", "_count_by",
    "_count_by_with_defaults", "_dedupe_findings", "_display_yaml_line_ranges", "_docstring_line_numbers",
    "_existing_files", "_exit_code_for_report", "_file_sha256", "_finding_record",
    "_frontend_e2e_legacy_route_context_allowlist", "_git_added_lines", "_git_blob_text", "_git_blob_text_prefix",
    "_git_merge_base", "_git_resolve_commit", "_git_tracked_paths", "_hard_gate_failing_count",
    "_has_scannable_text_name", "_high_spread_patterns", "_historical_route_authority_banner_line_numbers",
    "_hydromet_page_historical_context", "_infra_role_env_scan_files", "_is_display_boundary_context",
    "_is_scannable_dir", "_is_shell_assignment", "_iter_python_files", "_iter_text_files",
    "_line_continues_previous", "_line_continues_route_paragraph", "_line_has_active_route_instruction_context",
    "_line_has_active_route_valued_context", "_line_has_compatibility_context",
    "_line_has_complete_archive_status_marker", "_line_has_current_route_governing_context",
    "_line_has_display_env_section", "_line_has_evidence_boundary_context", "_line_has_historical_context",
    "_line_has_redirect_alias_context", "_line_has_route_redirect_arrow", "_line_has_terse_active_route_context",
    "_line_is_list_or_list_continuation", "_line_is_markdown_table_row", "_line_starts_markdown_fence",
    "_line_starts_markdown_heading", "_line_starts_markdown_list_item", "_line_starts_new_current_section",
    "_line_wraps_to_next", "_list_item_end_index", "_list_item_indent_width", "_list_item_start_index",
    "_makefile_line_has_unmanaged_python_tool", "_markdown_blockquote_depth", "_markdown_context_line",
    "_markdown_context_stripped", "_markdown_heading_level", "_markdown_indent_width", "_markdown_section_headings",
    "_matching_lines", "_matching_structural_added_lines", "_metadata", "_missing_text_needles", "_module_for_path",
    "_module_for_relative", "_module_heatmap", "_name_for_ast", "_normalize_scoped_context_text",
    "_normalized_apps_api_import_modules", "_normalized_reason_text", "_parent_list_item_indexes",
    "_path_has_compute_hint", "_path_has_display_hint", "_path_has_label", "_path_is_frontend_generated_artifact",
    "_path_is_legacy_route_token_scope", "_path_is_route_authority_expanded_scope",
    "_path_uses_markdown_route_context", "_period_is_sentence_boundary", "_physical_line_count",
    "_placeholder_path_allowlist_reason", "_preceding_context_lines", "_production_topology_scan_files",
    "_read_repo_text", "_read_structural_analysis_text", "_read_structural_header_text",
    "_read_structural_python_line_ranges", "_record_stale_route_mention_facts", "_rel",
    "_repo_relative_path_is_skipped", "_repo_text_rejection_reason", "_retired_active_tree_prefix_for",
    "_route_arrow_points_from_token", "_route_arrow_points_to_token", "_route_arrow_shape_for_bounds",
    "_route_arrow_shape_near_token", "_route_redirect_connector_segment", "_route_token_is_route_valued",
    "_same_list_item_following_lines", "_scoped_agent_context_finding_title", "_scoped_agent_context_findings",
    "_scoped_agent_context_markdown_lines", "_scoped_agent_context_owner_action", "_scoped_agent_context_record",
    "_scoped_agent_context_scope_record", "_scoped_agent_context_signal", "_scoped_agent_context_summary",
    "_section_archive_status_marker_ranges", "_section_heading_at", "_shell_command_name",
    "_shell_command_segments", "_slug", "_slurm_gateway_forbidden_call_reason",
    "_slurm_gateway_forbidden_path_reason", "_slurm_gateway_leakage_lines",
    "_slurm_gateway_router_name_is_forbidden", "_split_stale_route_active_clause_connectors",
    "_stale_route_allowlist_reason", "_stale_route_clause_analysis", "_stale_route_clause_ranges",
    "_stale_route_connector_splits_clause", "_stale_route_context_class", "_stale_route_duplicate_key",
    "_stale_route_governing_mention_text", "_stale_route_governing_text", "_stale_route_join_redirect_text",
    "_stale_route_line_context", "_stale_route_line_contexts", "_stale_route_line_matches",
    "_stale_route_list_governing_text", "_stale_route_list_governing_text_for_range",
    "_stale_route_list_redirect_governing_text", "_stale_route_list_redirect_governing_text_for_range",
    "_stale_route_list_redirect_governing_texts", "_stale_route_mention_clause_bounds",
    "_stale_route_mention_context", "_stale_route_mention_context_key", "_stale_route_mention_facts",
    "_stale_route_mention_facts_by_span", "_stale_route_mention_has_redirect_syntax",
    "_stale_route_mention_has_redirect_syntax_from_analysis", "_stale_route_mention_redirect_span",
    "_stale_route_mention_redirect_span_from_analysis", "_stale_route_mention_redirect_span_from_facts",
    "_stale_route_mention_redirect_text", "_stale_route_mention_semantic_key",
    "_stale_route_paragraph_governing_text", "_stale_route_paragraph_governing_text_for_range",
    "_stale_route_precomputed_semantic_key", "_stale_route_redirect_governing_text",
    "_stale_route_redirect_governing_text_for_line", "_stale_route_redirect_governing_texts",
    "_stale_route_structural_context", "_stale_route_table_governing_text",
    "_stale_route_table_governing_text_for_range", "_stale_route_table_redirect_governing_text",
    "_structural_added_import_families", "_structural_bounded_detail_token", "_structural_bounded_import_families",
    "_structural_bounded_public_surface_tokens", "_structural_bounded_token_component", "_structural_brace_index",
    "_structural_budget_exemption_record", "_structural_budget_file_record", "_structural_budget_owner_action",
    "_structural_budget_review_reason", "_structural_cjs_module_exports_object_bodies",
    "_structural_cjs_object_export_tokens", "_structural_comparison_base", "_structural_comparison_base_record",
    "_structural_current_import_families", "_structural_current_public_surface_tokens",
    "_structural_diff_truncation_detail", "_structural_file_budget_markdown_lines",
    "_structural_file_budget_summary", "_structural_growth_signal", "_structural_growth_signal_record",
    "_structural_import_families", "_structural_import_family", "_structural_import_family_detail",
    "_structural_import_family_detail_token", "_structural_line_spans", "_structural_new_public_surface_tokens",
    "_structural_next_open_brace", "_structural_ownership_growth_signals", "_structural_ownership_surface_signals",
    "_structural_path_is_source_like", "_structural_path_labels", "_structural_physical_line_count",
    "_structural_public_entrypoint_names", "_structural_public_surface_detail", "_structural_public_surface_label",
    "_structural_public_surface_tokens", "_structural_python_added_import_families",
    "_structural_python_current_context_public_surface_tokens", "_structural_python_import_block_families",
    "_structural_python_import_families", "_structural_python_import_families_from_tree",
    "_structural_python_import_paren_balance", "_structural_python_partial_public_surface_tokens",
    "_structural_python_public_name", "_structural_python_public_surface_tokens",
    "_structural_route_entrypoint_tokens", "_structural_route_owner_name_is_allowed",
    "_structural_route_owner_names", "_structural_route_path_token", "_structural_source_exemption",
    "_structural_source_rejection_reason", "_structural_split_top_level_object_items",
    "_structural_top_oversized_files_by_module", "_structural_top_oversized_modules",
    "_structural_tracked_source_paths", "_structural_ts_class_method_line_match",
    "_structural_ts_class_method_names", "_structural_ts_exported_class_method_tokens",
    "_structural_ts_ignored_spans", "_structural_ts_import_families", "_structural_ts_line_starts_static_import",
    "_structural_ts_named_export_tokens", "_structural_ts_position_is_ignored",
    "_structural_ts_public_surface_tokens", "_structural_ts_regex_literal_allowed_at",
    "_structural_ts_regex_literal_end", "_structural_ts_static_import_blocks",
    "_structural_ts_static_import_can_continue", "_structural_ts_static_import_module",
    "_structural_unknown_line_count_file_record", "_summarize_added_line_matches", "_summary_counts",
    "_text_contains_needle", "_text_has_historical_marker", "_text_has_route_authority_marker",
    "_topology_authority_list_item_path", "_topology_authority_path_normalize", "_topology_authority_paths",
    "_topology_context_has_complete_node22_local_pg_boundary",
    "_topology_context_has_current_node22_local_postgres_use",
    "_topology_context_has_data_plane_writer_or_mirror_terms", "_topology_context_has_direct_display_env_source",
    "_topology_context_has_display_env_authority_prose", "_topology_context_has_display_env_prohibition",
    "_topology_context_has_indirect_display_env_source", "_topology_context_has_negated_archive_or_stop_state",
    "_topology_context_has_negative_mirror_boundary", "_topology_context_has_negative_node22_db_access",
    "_topology_context_has_negative_node22_writer_boundary",
    "_topology_context_has_negative_writer_or_mirror_terms",
    "_topology_context_has_node22_local_postgres_use_action",
    "_topology_context_has_stale_pending_retirement_state", "_topology_context_has_unnegated_archived_state",
    "_topology_context_has_unnegated_display_env_source", "_topology_context_has_unnegated_stopped_state",
    "_topology_context_is_compatibility_mirror_contract", "_topology_context_is_explicit_mirror_implementation",
    "_topology_context_is_guardrail_or_test_meta", "_topology_context_is_historical_receipt_evidence",
    "_topology_context_is_non_current", "_topology_context_is_pre_cutover_historical_evidence",
    "_topology_context_is_retirement_or_rejection_boundary",
    "_topology_context_is_structured_node22_local_pg_boundary", "_topology_context_references_display_env_path",
    "_topology_context_sources_display_env", "_topology_contract_context", "_topology_declared_current_authorities",
    "_topology_display_env_associated_writer", "_topology_display_env_association_context",
    "_topology_display_env_context", "_topology_display_env_context_is_allowed", "_topology_display_env_facts",
    "_topology_display_env_file_allows_file_level_association", "_topology_document_is_non_current",
    "_topology_finding", "_topology_forward_claim_context", "_topology_line_context",
    "_topology_line_declares_document_superseded", "_topology_line_display_env_alias_name",
    "_topology_line_has_data_plane_writer_command", "_topology_line_has_node22_database_url_scan_drift",
    "_topology_line_has_node22_db_writer_drift", "_topology_line_has_node22_local_postgres_or_mirror_drift",
    "_topology_line_has_non_current_or_compatibility_marker", "_topology_line_has_psql_context_mutation_command",
    "_topology_line_has_psql_mutation_command", "_topology_line_has_shell_source_command",
    "_topology_line_has_unnegated_data_plane_writer_or_mirror_use",
    "_topology_line_has_unnegated_direct_display_env_source", "_topology_line_invokes_psql",
    "_topology_line_is_comment_only", "_topology_line_is_object_store_copy",
    "_topology_line_is_standalone_node22_anchor", "_topology_line_may_have_node22_db_writer_drift",
    "_topology_line_may_source_display_env", "_topology_line_may_start_node22_db_writer_claim",
    "_topology_line_mentions_mirror", "_topology_line_mentions_rollback", "_topology_line_sources_display_env",
    "_topology_line_sources_display_env_alias", "_topology_local_block_context",
    "_topology_local_postgres_context_is_allowed", "_topology_mentions_active_primary_database_authority",
    "_topology_mentions_database", "_topology_mentions_node22", "_topology_mentions_writer",
    "_topology_node22_db_writer_clause_is_allowed", "_topology_node22_db_writer_context_is_allowed",
    "_topology_node22_db_writer_drift_clauses", "_topology_node22_writer_claim_context", "_topology_normalized",
    "_topology_path_is_archive_or_generated", "_topology_prefix_has_display_env_source_negation",
    "_topology_psql_heredoc_token", "_topology_relation_clauses", "_topology_strip_db_absence_claims",
    "_topology_strip_shell_comment", "_topology_top_context_declares_whole_document_non_current",
    "_whole_document_archive_status_marker_range", "_yaml_service_looks_display_facing", "annotations", "argparse",
    "ast", "bisect_left", "bisect_right", "build_report", "dataclass", "datetime", "defaultdict", "fnmatch",
    "hashlib", "json", "main", "os", "re", "render_markdown", "repo_root_from", "shlex", "stat", "subprocess",
    "sys", "textwrap",
]


# --- #1842 compatibility facade -------------------------------------------
# Same mechanism, same reason as the #1099 refresh facade
# (`scripts/scheduler_file_provider_refresh.py`) and the #1100 publish facade.
# Pre-split this file WAS the namespace: one binding per name, so
# `monkeypatch.setattr(audit_repo_entropy, name, stub)` was observed by every
# call site, and `write_entropy_baseline.audit_repo_entropy.<name>` resolved to
# that same binding.  Post-split the same logical binding is replicated across
# the `scripts/governance/entropy_audit/` modules that import it, and a plain
# re-export here would leave those replicas stale -- the patch would succeed,
# the stub would never be called, and the negative tests built on it (the eight
# patched stale-route/topology helpers with call sites, plus the writer's
# `build_report` / `_git_tracked_paths` seams) would pass vacuously.  The module
# class below restores the single-namespace semantics by broadcasting every
# attribute write on this module to each package module that currently binds the
# SAME object under that name (identity-matched once, at import).  Undo restores
# travel the same path.  `subprocess` is in the mirror table for the same
# reason: the corpus patches `audit_repo_entropy.subprocess.run`.
_ENTROPY_AUDIT_PACKAGE_MODULES: tuple[ModuleType, ...] = (
    _mod_constants,
    _mod_schema,
    _mod_repo_files,
    _mod_findings,
    _mod_archive_status,
    _mod_route_governing_text,
    _mod_route_mentions,
    _mod_check_stale_routes,
    _mod_topology_predicates,
    _mod_topology_context_rules,
    _mod_topology_display_env,
    _mod_check_topology,
    _mod_check_env_and_tokens,
    _mod_check_paths_and_api,
    _mod_structural_sources,
    _mod_structural_surface,
    _mod_structural_growth,
    _mod_structural_budget,
    _mod_facade_guard,
    _mod_scoped_context,
    _mod_report,
)


def _mirrored_bindings() -> dict[str, tuple[ModuleType, ...]]:
    """Map facade attribute -> package modules holding the identical binding."""

    bindings: dict[str, tuple[ModuleType, ...]] = {}
    for name, value in list(globals().items()):
        if name.startswith("__"):
            continue
        owners = tuple(
            module
            for module in _ENTROPY_AUDIT_PACKAGE_MODULES
            if name in module.__dict__ and module.__dict__[name] is value
        )
        if owners:
            bindings[name] = owners
    return bindings


_MIRRORED_BINDINGS: dict[str, tuple[ModuleType, ...]] = _mirrored_bindings()


class _AuditFacadeModule(ModuleType):
    """Facade module type that mirrors attribute writes onto the real owners."""

    def __setattr__(self, name: str, value: Any) -> None:
        ModuleType.__setattr__(self, name, value)
        for module in _MIRRORED_BINDINGS.get(name, ()):
            ModuleType.__setattr__(module, name, value)

    def __delattr__(self, name: str) -> None:
        ModuleType.__delattr__(self, name)
        for module in _MIRRORED_BINDINGS.get(name, ()):
            if name in module.__dict__:
                ModuleType.__delattr__(module, name)


sys.modules[__name__].__class__ = _AuditFacadeModule


if __name__ == "__main__":
    sys.exit(main())
