job_type_templates:
  download_source_cycle: download_source_cycle.sbatch
  convert_canonical: convert_canonical.sbatch
  produce_forcing_array: produce_forcing_array.sbatch
  run_shud_forecast_array: run_shud_forecast_array.sbatch
  parse_output_array: parse_output_array.sbatch
  compute_frequency_array: compute_frequency_array.sbatch
  publish_tiles: publish_tiles.sbatch
