#!/usr/bin/env bash
# node-27 canonical-retention system unit installer (issue #2360, design D6).
#
# Run ONCE by the operator, as root:
#
#   sudo /home/nwm/NWM/scripts/node27_canonical_retention_install.sh
#
# and again after ANY change to the nwm raw-retention env
# (/home/nwm/NWM/infra/env/node27-raw-retention.env): the system unit's env is a
# snapshot generated from it here, not a live link.
#
# What it does, after fail-closed preconditions (nothing is written before all
# of them pass):
#   1. /etc/nhms (0755 root) and /etc/nhms/node27-canonical-retention.env --
#      the nwm env minus the per-unit keys, plus LANES=canonical and a log root
#      and flock path outside /home/nwm; owner frd_muziyao, mode 0600 (the
#      wrapper refuses anything else). Values are never printed.
#   2. install -m 0644 the two canonical-retention units and the system alert
#      template from infra/systemd/system/ into /etc/systemd/system/,
#      daemon-reload, enable --now the timer.
#   3. one synchronous start of the service, then print its Result, the timer
#      state, the newest summary's lanes/counts/lock failures and the lock
#      file's mode/owner. Exits non-zero unless the service Result is success.
#
# The copyback lock file is only ever inspected, never created or changed: its
# `0600` / owner contract is exactly why the canonical lane runs as its owner.
# Rollback: docs/runbooks/current-production-ops.md "node-27 canonical 删除持锁".

set -euo pipefail

readonly REPO=/home/nwm/NWM
readonly UNIT_USER=frd_muziyao
readonly UNIT_UID=1103
readonly OBJECT_STORE_ROOT=/home/ghdc/nwm/object-store
readonly COPYBACK_LOCK="$OBJECT_STORE_ROOT/.nhms-copyback-batch.lock"
readonly SOURCE_ENV="$REPO/infra/env/node27-raw-retention.env"
readonly ENV_DIR=/etc/nhms
readonly TARGET_ENV="$ENV_DIR/node27-canonical-retention.env"
readonly LOG_DIR=/var/log/nhms-node27-canonical-retention
readonly RUN_LOCK=/run/nhms-node27-canonical-retention/raw-retention.lock
readonly UNIT_SOURCE_DIR="$REPO/infra/systemd/system"
readonly UNIT_TARGET_DIR=/etc/systemd/system
readonly SERVICE=nhms-node27-canonical-retention.service
readonly TIMER=nhms-node27-canonical-retention.timer
readonly UNIT_FILES=(
  nhms-node27-canonical-retention.service
  nhms-node27-canonical-retention.timer
  nhms-node27-system-unit-failure-alert@.service
)
# Keys the nwm env may set that must not reach the canonical unit: the lane
# selection and every path that would point into /home/nwm or collide with the
# nwm unit's log/flock files.
readonly PER_UNIT_KEYS_RE='^[[:space:]]*(export[[:space:]]+)?NODE27_RAW_RETENTION_(LANES|LOG_ROOT|LOCK_PATH|LOG_FILE|SUMMARY_PATH|BOOTSTRAP_LOG)='

note() { echo "node27-canonical-retention-install: $*" >&2; }
refuse() {
  note "REFUSED: $*"
  exit 1
}

# The generated env, on stdout: the source env without the per-unit keys, then
# this unit's values. Kept as a function so its filter can be tested without
# root (`source` this file; `main` only runs when executed).
render_canonical_env() {
  local source_env="$1" rc=0
  grep -Ev "$PER_UNIT_KEYS_RE" "$source_env" || rc=$?
  # grep exits 1 when every line was filtered (or the file is empty); only
  # rc >= 2 is a read error.
  if [ "$rc" -gt 1 ]; then
    return "$rc"
  fi
  printf '%s\n' \
    "# Generated by scripts/node27_canonical_retention_install.sh from $source_env." \
    "# Do not edit: rerun the installer after changing the source env." \
    "NODE27_RAW_RETENTION_LANES=canonical" \
    "NODE27_RAW_RETENTION_LOG_ROOT=$LOG_DIR" \
    "NODE27_RAW_RETENTION_LOCK_PATH=$RUN_LOCK"
}

# The value of KEY in an env file, read as text and never sourced (this runs as
# root on a file nwm owns). Accepted shape: KEY assigned on exactly one line,
# `[export ]KEY=value`, value optionally in one pair of '...' or "..." -- so the
# wrapper's `set -a; .` (last assignment wins) sees the same value. Zero or
# several assignments: rc 1.
env_file_value() {
  local file="$1" key="$2" re value
  re="^[[:space:]]*(export[[:space:]]+)?${key}="
  [ "$(grep -cE "$re" "$file")" = 1 ] || return 1
  value=$(grep -E "$re" "$file")
  value=${value#*=}
  case "$value" in
    \"*\") value=${value#\"}; value=${value%\"} ;;
    \'*\') value=${value#\'}; value=${value%\'} ;;
  esac
  printf '%s\n' "$value"
}

check_copyback_lock() {
  local lock="$1"
  # Never created here: a missing lock file is a node-22 / copyback-root
  # problem, not something this installer may paper over.
  if [ ! -f "$lock" ] || [ -L "$lock" ]; then
    refuse "copyback lock $lock is missing or not a regular file"
  fi
  [ "$(stat -c %u "$lock")" = "$UNIT_UID" ] || refuse "copyback lock is not owned by uid $UNIT_UID"
  [ "$(stat -c %a "$lock")" = "600" ] || refuse "copyback lock mode is not 600"
}

# The nwm env is the source of the generated env AND the nwm unit's own env:
# it must already keep the nwm unit off the canonical lane (otherwise that unit
# records canonical `lock_unsafe` every tick) and name the object-store root
# checked above.
check_source_env() {
  local env="$1" lanes lane root
  local -a names
  if [ ! -f "$env" ] || [ -L "$env" ]; then
    refuse "source env $env is missing or a symlink"
  fi
  [ "$(stat -c %a "$env")" = "600" ] || refuse "source env $env mode is not 600"

  lanes=$(env_file_value "$env" NODE27_RAW_RETENTION_LANES) \
    || refuse "source env must set NODE27_RAW_RETENTION_LANES on exactly one line (raw,precip-cache)"
  lanes=${lanes// /}
  [ -n "${lanes//,/}" ] || refuse "source env NODE27_RAW_RETENTION_LANES names no lane"
  IFS=, read -r -a names <<<"$lanes"
  for lane in "${names[@]}"; do
    case "$lane" in
      raw | precip-cache | "") ;;
      *) refuse "source env NODE27_RAW_RETENTION_LANES may name only raw / precip-cache" ;;
    esac
  done

  root=$(env_file_value "$env" NODE27_RAW_RETENTION_OBJECT_STORE_ROOT) \
    || refuse "source env must set NODE27_RAW_RETENTION_OBJECT_STORE_ROOT on exactly one line"
  [ "$root" = "$OBJECT_STORE_ROOT" ] \
    || refuse "source env NODE27_RAW_RETENTION_OBJECT_STORE_ROOT is not $OBJECT_STORE_ROOT"
}

check_preconditions() {
  [ "$(id -u)" -eq 0 ] || refuse "must run as root (sudo $0)"

  local uid
  uid=$(id -u "$UNIT_USER" 2>/dev/null) || refuse "user $UNIT_USER does not exist"
  [ "$uid" = "$UNIT_UID" ] || refuse "$UNIT_USER is uid $uid, expected $UNIT_UID"

  if [ ! -d "$OBJECT_STORE_ROOT" ] || [ -L "$OBJECT_STORE_ROOT" ]; then
    refuse "object-store root $OBJECT_STORE_ROOT is not a real directory"
  fi
  [ "$(stat -c %u "$OBJECT_STORE_ROOT")" = "$UNIT_UID" ] \
    || refuse "object-store root is not owned by uid $UNIT_UID"

  check_copyback_lock "$COPYBACK_LOCK"

  local unit
  for unit in "${UNIT_FILES[@]}"; do
    if [ ! -f "$UNIT_SOURCE_DIR/$unit" ] || [ -L "$UNIT_SOURCE_DIR/$unit" ]; then
      refuse "repo unit $UNIT_SOURCE_DIR/$unit is missing or a symlink"
    fi
  done

  check_source_env "$SOURCE_ENV"

  # The unit user must be able to import the runner from the nwm checkout
  # through the nwm venv (directory modes, uv interpreter tree).
  (cd "$REPO" && runuser -u "$UNIT_USER" -- env PYTHONPATH="$REPO" "$REPO/.venv/bin/python" \
    -c 'import psycopg2, scripts.node27_raw_retention') \
    || refuse "import probe as $UNIT_USER failed"
}

write_env() {
  install -d -m 0755 -o root -g root "$ENV_DIR"
  umask 077
  local tmp
  tmp=$(mktemp "$ENV_DIR/.node27-canonical-retention.env.XXXXXX")
  # shellcheck disable=SC2064
  trap "rm -f -- '$tmp'" EXIT
  render_canonical_env "$SOURCE_ENV" > "$tmp"
  chown "$UNIT_USER" "$tmp"
  chmod 600 "$tmp"
  mv -f -- "$tmp" "$TARGET_ENV"
  trap - EXIT
  note "wrote $TARGET_ENV ($(stat -c '%a %U' "$TARGET_ENV"); values not shown)"
}

install_units() {
  local unit
  for unit in "${UNIT_FILES[@]}"; do
    install -m 0644 -o root -g root "$UNIT_SOURCE_DIR/$unit" "$UNIT_TARGET_DIR/$unit"
  done
  systemctl daemon-reload
  systemctl enable --now "$TIMER"
}

report_newest_summary() {
  "$REPO/.venv/bin/python" - "$LOG_DIR" <<'PY' || true
import json
import sys
from pathlib import Path

summaries = sorted(Path(sys.argv[1]).glob("raw-retention-*.json"), key=lambda p: p.stat().st_mtime)
if not summaries:
    print("newest summary: none")
    raise SystemExit(0)
payload = json.loads(summaries[-1].read_text(encoding="utf-8"))
print(f"newest summary: {summaries[-1]}")
print(json.dumps({key: payload.get(key) for key in (
    "status", "execution_mode", "lanes", "cutoff", "retention_days", "sources",
    "counts", "copyback_lock_failures",
)}, sort_keys=True))
PY
}

main() {
  check_preconditions
  write_env
  install_units

  local start_rc=0
  systemctl start "$SERVICE" || start_rc=$?
  note "systemctl start $SERVICE rc=$start_rc"

  systemctl show "$SERVICE" -p User,Result,ExecMainStatus
  echo "timer: $(systemctl is-active "$TIMER" || true)"
  systemctl list-timers "$TIMER" --no-pager || true
  report_newest_summary
  echo "copyback lock: $(stat -c '%A %U' "$COPYBACK_LOCK")"

  local result
  result=$(systemctl show "$SERVICE" -p Result --value)
  if [ "$result" != "success" ]; then
    note "FAILED: $SERVICE Result=$result"
    exit 1
  fi
  note "OK: $SERVICE Result=success"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  main "$@"
fi
