"""Scan scope, thresholds, schema versions and compiled patterns of the audit.

Split out of ``scripts/governance/audit_repo_entropy.py`` by #1842; every name
here is verbatim from that module and stays importable from it. This module is
the bottom of the package: it holds no logic, only the tuples/frozensets that
fix what the audit scans and the ``re`` patterns each check family matches with."""

from __future__ import annotations

import re

AXES = ("structure", "semantics", "behavior", "context", "protocol", "control")


CHECK_FAMILIES = (
    "role-env-boundary",
    "production-topology-node22-db-writer",
    "production-topology-node22-local-postgres",
    "production-topology-display-env-writer",
    "qhh-diagnostic-token",
    "paused-workflow-condition",
    "broad-e2e-api-mock",
    "stale-display-route-token",
    "placeholder-path-token",
    "placeholder-path-exists",
    "makefile-toolchain-discipline",
    "openapi-frontend-types-delegated",
    "openapi-frontend-types-presence",
    "openapi-frontend-types-signal",
    "slurm-gateway-route-leakage",
    "agent-artifact-ownership-policy",
    "agent-artifact-ignore-policy",
    "tracked-generated-artifact",
    "apps-api-layer-inversion",
    "compatibility-facade-growth",
    "scoped-agent-context",
)


RETIRED_ACTIVE_TREE_PREFIXES = (
    "apps/web",
    "workers/forcing-producer",
    "workers/shud-runtime",
    "workers/output-parser",
    "workers/sbatch_templates",
    "services/tile-publisher",
)


HARD_GATE_CHECK_IDS = (
    "agent-artifact-ignore-policy",
    "agent-artifact-ownership-policy",
    "broad-e2e-api-mock",
    "makefile-toolchain-discipline",
    "openapi-frontend-types-presence",
    "paused-workflow-condition",
    "production-topology-display-env-writer",
    "production-topology-node22-db-writer",
    "production-topology-node22-local-postgres",
    "qhh-diagnostic-token",
    "role-env-boundary",
    "slurm-gateway-route-leakage",
    "tracked-generated-artifact",
)


SEVERITY_RANK = {"low": 1, "medium": 2, "high": 3}


PRIORITY_RANK = {"P3": 1, "P2": 2, "P1": 3, "P0": 4}


SCORE_RANK = {"low": 1, "medium": 2, "high": 3}


RANK_SCORE = {1: "low", 2: "medium", 3: "high"}


SCAN_SKIP_DIRS = frozenset(
    {
        ".git",
        ".venv",
        "node_modules",
        "dist",
        "__pycache__",
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
        ".cache",
    }
)


SCAN_SKIP_ROOT_DIRS = frozenset({"artifacts", "data"})


SCAN_SKIP_PREFIXES = (".nhms-",)


TEXT_EXTENSIONS = frozenset(
    {
        ".cfg",
        ".css",
        ".env",
        ".example",
        ".html",
        ".ini",
        ".js",
        ".json",
        ".jsx",
        ".lock",
        ".md",
        ".mjs",
        ".py",
        ".rst",
        ".sh",
        ".sql",
        ".toml",
        ".ts",
        ".tsx",
        ".txt",
        ".yaml",
        ".yml",
    }
)


STRUCTURAL_FILE_BUDGET_YELLOW_MIN_LINES = 500


STRUCTURAL_FILE_BUDGET_MANDATORY_OVER_LINES = 1000


STRUCTURAL_FILE_BUDGET_TOP_LIMIT = 10


STRUCTURAL_FILE_BUDGET_SCHEMA_VERSION = "governance-7.structural-file-budget.v1"


COMPATIBILITY_FACADE_GUARD_SCHEMA_VERSION = "governance-7.compatibility-facade-guard.v1"


COMPATIBILITY_FACADE_GUARD_CHECK_ID = "compatibility-facade-growth"


SCOPED_AGENT_CONTEXT_SCHEMA_VERSION = "governance-7.scoped-agent-context.v1"


SCOPED_AGENT_CONTEXT_CHECK_ID = "scoped-agent-context"


SCOPED_AGENT_CONTEXT_GLOSSARY_PATH = "openspec/glossary.md"


SCOPED_AGENT_CONTEXT_SPEC_PATH = (
    "openspec/changes/governance-7-structural-entropy-controls/"
    "specs/scoped-agent-context-governance/spec.md"
)


STRUCTURAL_BUDGET_BASE_REF_ENV = "NHMS_STRUCTURAL_BUDGET_BASE_REF"


STRUCTURAL_GENERATED_HEADER_BYTES = 8192


STRUCTURAL_GENERATED_HEADER_LINES = 20


STRUCTURAL_SOURCE_EXTENSIONS = frozenset(
    {
        ".cjs",
        ".css",
        ".env",
        ".html",
        ".ini",
        ".js",
        ".json",
        ".jsx",
        ".mjs",
        ".proto",
        ".py",
        ".sh",
        ".sql",
        ".toml",
        ".ts",
        ".tsx",
        ".yaml",
        ".yml",
    }
)


STRUCTURAL_SOURCE_FILENAMES = frozenset({"Makefile", ".dockerignore", ".gitignore"})


STRUCTURAL_SOURCE_ROOTS = frozenset(
    {
        ".github",
        "apps",
        "config",
        "data",
        "db",
        "infra",
        "openapi",
        "packages",
        "schemas",
        "scripts",
        "services",
        "tests",
        "workers",
    }
)


STRUCTURAL_PROTOCOL_ROOTS = frozenset({"openapi", "schemas"})


STRUCTURAL_GENERATED_LABELS = frozenset(
    {"autogen", "autogenerated", "generated", "generateds", "gen", "openapi-types"}
)


STRUCTURAL_FIXTURE_LABELS = frozenset(
    {"__fixtures__", "fixture", "fixtures", "mock", "mocked", "mocks", "snapshot", "snapshots", "testdata"}
)


STRUCTURAL_DEPENDENCY_LOCKFILE_NAMES = frozenset(
    {
        "Cargo.lock",
        "package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)


STRUCTURAL_IMPORT_FAMILY_MIXED_COUNT = 4


COMPATIBILITY_FACADE_PROJECT_IMPORT_ROOTS = frozenset({"apps", "packages", "services", "workers"})


MAX_SCANNED_TEXT_FILE_BYTES = 1_048_576


MAX_ARTIFACT_FINGERPRINT_BYTES = 1_048_576


HASH_CHUNK_BYTES = 1_048_576


STRUCTURAL_DIFF_READ_CHUNK_BYTES = 65_536


STRUCTURAL_DIFF_MAX_LINE_BYTES = 65_536


STRUCTURAL_TS_STATIC_IMPORT_MAX_BLOCK_LINES = 80


STRUCTURAL_PYTHON_CONTEXT_MAX_LINES = 200


STRUCTURAL_PUBLIC_SURFACE_DETAIL_TOKEN_LIMIT = 10


STRUCTURAL_TOKEN_COMPONENT_MAX_CHARS = 96


STRUCTURAL_TOKEN_HASH_HEX_CHARS = 16


COMPLETE_ARCHIVE_STATUS_ALLOWLIST_REASON = (
    "complete archive status marker declares preserved non-current evidence"
)


ARCHIVE_STATUS_RECOGNIZED_FIELDS = frozenset(
    {
        "status",
        "current_authority",
        "superseded_by",
        "status_since",
        "archive_scope",
        "retained_for",
    }
)


ARCHIVE_STATUS_REQUIRED_FIELDS = frozenset(
    {
        "status",
        "current_authority",
        "status_since",
        "archive_scope",
        "retained_for",
    }
)


ARCHIVE_STATUS_REQUIRED_FIELDS_BY_STATUS: dict[str, frozenset[str]] = {
    "historical baseline": ARCHIVE_STATUS_REQUIRED_FIELDS,
    "superseded": ARCHIVE_STATUS_REQUIRED_FIELDS | frozenset({"superseded_by"}),
    "archived": ARCHIVE_STATUS_REQUIRED_FIELDS | frozenset({"superseded_by"}),
}


ARCHIVE_STATUS_NON_CURRENT_VALUES = frozenset({"historical baseline", "superseded", "archived"})


ARCHIVE_STATUS_FRONT_MATTER_MAX_LINES = 200


LEGACY_DISPLAY_ROUTE_TOKENS = ("/hydro-met", "HydroMetPage")


LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN = (
    r"(?P<token>"
    r"/(?:overview|hydro-met|forecast|meteorology)"
    r"|/(?:basins|segments)/(?::[A-Za-z][A-Za-z0-9_-]*|[A-Za-z0-9][A-Za-z0-9_-]*)"
    r")"
    r"(?=$|[^A-Za-z0-9_/-])"
)


ROUTE_BASE_PLACEHOLDER_PATTERN = (
    r"(?:"
    r"\$[A-Za-z_][A-Za-z0-9_]*"
    r"|\$\{[A-Za-z_][A-Za-z0-9_]*\}"
    r"|<[A-Za-z][A-Za-z0-9_-]*>"
    r")"
)


LEGACY_DISPLAY_ROUTE_PATTERN = re.compile(LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN)


LEGACY_DISPLAY_ROUTE_BOUNDARY_PATTERN = re.compile(
    r"(?:^|"
    + ROUTE_BASE_PLACEHOLDER_PATTERN
    + r"|[\s`'\"([{<|=?:&]|https?://[^/\s`'\"()<>{}]+)"
    + LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN
)


ROUTE_VALUED_LEGACY_DISPLAY_ROUTE_PATTERN = re.compile(
    r"(?:"
    + ROUTE_BASE_PLACEHOLDER_PATTERN
    + r"|--[A-Za-z][A-Za-z0-9_-]*="
    r"|[?&][A-Za-z][A-Za-z0-9_-]*="
    r"|[A-Za-z_][A-Za-z0-9_]*="
    r")"
    + LEGACY_DISPLAY_ROUTE_TOKEN_PATTERN
)


HYDROMET_PAGE_IDENTIFIER_PATTERN = re.compile(r"(?<![A-Za-z0-9_])HydroMetPage(?![A-Za-z0-9_])")


ROUTE_REDIRECT_TARGET_PATTERN = re.compile(r"(?:^|[\s`'\"([{<|])/(?:$|[\s`'\"()\]}>.,;:?|]|redirect|alias)")


ROUTE_REDIRECT_WORD_PATTERN = re.compile(r"\b(?:redirects?|redirected)\b|legacyredirect|重定向", re.IGNORECASE)


ROUTE_ACTIVE_CLAUSE_CONNECTOR_PATTERN = re.compile(
    r"\b(?:and|then)\s+(?:open|visit|browse|navigate|use)\b|且打开",
    re.IGNORECASE,
)


BROAD_E2E_API_MOCK_PATTERN = re.compile(
    r"(?<![A-Za-z0-9_$])page\.route\s*\(\s*(?P<glob>(?P<quote>['\"])\*\*/api/v1/\*\*(?P=quote))",
    re.MULTILINE,
)


MARKDOWN_TABLE_SEPARATOR_PATTERN = re.compile(r"^\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$")


MARKDOWN_LIST_ITEM_PATTERN = re.compile(r"^(?P<indent>\s*)(?:[-*+]|\d+[.)])\s+")


MARKDOWN_HEADING_PATTERN = re.compile(r"^\s{0,3}#{1,6}\s+")


MARKDOWN_BLOCKQUOTE_PREFIX_PATTERN = re.compile(r"^\s{0,3}>\s?")


TOPOLOGY_DISPLAY_ENV_PATH_PATTERN = re.compile(
    r"(?<![a-z0-9_.-])"
    r"/?"
    r"(?:(?:['\"]?\$\{?[a-z_][a-z0-9_]*\}?['\"]?|~|\.{1,2}|[a-z0-9_.-]+)\/)*"
    r"infra/env/display\.env"
    r"(?![a-z0-9_.-])"
)


TOPOLOGY_DISPLAY_ENV_SOURCE_TO_WRITER_MAX_LINES = 120


TOPOLOGY_PSQL_HEREDOC_MAX_LOOKAHEAD = 80


TOPOLOGY_SQL_MUTATION_VERB_PATTERN = re.compile(
    r"\b(?:insert|update|delete|truncate|create|alter|drop|grant|revoke|copy|merge)\b"
)


STRUCTURAL_TS_STATIC_BARE_IMPORT_PATTERN = re.compile(
    r"^\s*import(?:[ \t]+type)?[ \t]*(?P<quote>['\"])(?P<module>[^'\"]+)(?P=quote)"
)


STRUCTURAL_TS_STATIC_FROM_IMPORT_PATTERN = re.compile(
    r"\bfrom[ \t]*(?P<quote>['\"])(?P<module>[^'\"]+)(?P=quote)"
)


STRUCTURAL_TS_REQUIRE_PATTERN = re.compile(
    r"\brequire[ \t]*\([ \t]*(?P<quote>['\"])(?P<module>[^'\"]+)(?P=quote)[ \t]*\)"
)


STRUCTURAL_TS_DYNAMIC_IMPORT_PATTERN = re.compile(
    r"\bimport[ \t]*\([ \t]*(?P<quote>['\"])(?P<module>[^'\"]+)(?P=quote)[ \t]*\)"
)


STRUCTURAL_PYTHON_DECLARATION_PATTERN = re.compile(
    r"^(?P<indent>[ \t]*)(?:(?P<class>class)|(?:(?:async[ \t]+)?def))[ \t]+"
    r"(?P<name>[A-Za-z][A-Za-z0-9_]*)\b"
)


STRUCTURAL_PUBLIC_TS_PATTERN = re.compile(
    r"^\s*export\s+(?P<default>default\s+)?"
    r"(?:(?:async|abstract|declare)\s+)*"
    r"(?:function|class|const|let|var|interface|type|enum)\s+(?P<name>[A-Za-z][A-Za-z0-9_]*)\b",
    re.MULTILINE,
)


STRUCTURAL_TS_EXPORTED_CLASS_PATTERN = re.compile(
    r"^\s*export\s+(?:default\s+)?(?:(?:abstract|declare)\s+)*"
    r"class\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\b",
    re.MULTILINE,
)


STRUCTURAL_TS_NAMED_EXPORT_PATTERN = re.compile(
    r"^\s*export\s*{\s*(?P<body>[^}]+)\s*}(?:\s+from\s+['\"][^'\"]+['\"])?\s*;?",
    re.MULTILINE,
)


STRUCTURAL_TS_DEFAULT_EXPORT_PATTERN = re.compile(r"^\s*export\s+default\b", re.MULTILINE)


STRUCTURAL_CJS_EXPORTS_ASSIGNMENT_PATTERN = re.compile(
    r"^\s*(?:module\.)?exports\.(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*=",
    re.MULTILINE,
)


STRUCTURAL_CJS_MODULE_EXPORTS_OBJECT_START_PATTERN = re.compile(
    r"^\s*module\.exports\s*=\s*{",
    re.MULTILINE,
)


STRUCTURAL_CJS_MODULE_EXPORTS_DEFAULT_PATTERN = re.compile(
    r"^\s*module\.exports\s*=(?!\s*{)",
    re.MULTILINE,
)


STRUCTURAL_ROUTE_OWNER_ASSIGNMENT_PATTERN = re.compile(
    r"^\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*"
    r"(?:[A-Za-z_][A-Za-z0-9_]*\.)?(?:FastAPI|APIRouter)\s*\(",
    re.MULTILINE,
)


STRUCTURAL_ROUTE_ENTRYPOINT_PATTERN = re.compile(
    r"^\s*@(?P<owner>[A-Za-z_][A-Za-z0-9_]*)\."
    r"(?P<method>get|post|put|patch|delete|options|head)"
    r"\s*\(\s*(?P<quote>['\"])(?P<path>[^'\"]*)(?P=quote)",
    re.MULTILINE,
)


STRUCTURAL_COMPATIBILITY_PATTERN = re.compile(
    r"\b(?:compat|compatibility|legacy|deprecated|alias|re-?export|monkeypatch|shim)\b|__all__",
    re.IGNORECASE,
)


STRUCTURAL_PARSER_VALIDATOR_PATTERN = re.compile(
    r"\b(?:parse|parser|validate|validator|validation|schema|deserialize|serialize|normalize)\b",
    re.IGNORECASE,
)


STRUCTURAL_DIFF_HUNK_PATTERN = re.compile(
    r"^@@ -\d+(?:,\d+)? \+(?P<start>\d+)(?:,(?P<count>\d+))? @@(?: .*)?$"
)
