export const m11VisualTokens = {
  navHeight: '0px',
  leftPanelWidth: '280px',
  rightPanelWidth: '340px',
  rightPanelMinWidth: '320px',
  rightPanelMaxWidth: '360px',
  timelineHeight: '64px',
  spacingUnit: '4px',
  radiusSm: '4px',
  radiusMd: '8px',
  fontBody: '14px',
  fontCaption: '12px',
  fontTitle: '16px',
  fontMetric: '24px',
  statuses: {
    success: '#4CAF50',
    warning: '#FF9800',
    danger: '#F44336',
    info: '#2196F3',
  },
} as const
